package com.adaptiq.tutor.engine

import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import android.util.Log

/**
 * MnnBridge - Kotlin wrapper around the MNN native C++ LLM inference engine.
 *
 * Converts JNI token callbacks into reactive Kotlin [Flow<String>] streams
 * using [callbackFlow], enabling seamless integration with Jetpack Compose UI.
 *
 * Architecture:
 * ```
 * Compose UI  ←  StateFlow  ←  TutorViewModel  ←  MnnBridge.generateStream()
 *                                                      ↓  (callbackFlow)
 *                                            NativeTokenCallback.onToken()
 *                                                      ↑  (JNI callback)
 *                                     C++  LlmStreamBuffer → Llm::response(ostream*)
 * ```
 *
 * Usage:
 * ```
 * val bridge = MnnBridge()
 * bridge.loadModel("/data/local/tmp/model/config.json")
 * bridge.generateStream("Explain photosynthesis")
 *     .collect { token -> updateUI(token) }
 * ```
 */
class MnnBridge {

    companion object {
        private const val TAG = "MnnBridge"

        init {
            try {
                // Load the monolithic MNN library (includes LLM engine)
                System.loadLibrary("MNN")
                // Load our JNI bridge
                System.loadLibrary("adaptiq_jni")
                Log.i(TAG, "Native libraries loaded successfully")
            } catch (e: UnsatisfiedLinkError) {
                Log.e(TAG, "Failed to load native libraries: ${e.message}")
                throw RuntimeException("MNN native libraries not available", e)
            }
        }
    }

    // ─── JNI Native Methods ──────────────────────────────────────
    private external fun nativeCreateLLM(configPath: String): Boolean
    private external fun nativeSetConfig(configJson: String): Boolean
    private external fun nativeGenerateStream(prompt: String, callback: NativeTokenCallback)
    private external fun nativeGenerateWithHistory(
        roles: Array<String>,
        contents: Array<String>,
        callback: NativeTokenCallback
    )
    private external fun nativeCancelGeneration()
    private external fun nativeReset()
    private external fun nativeReleaseModel()
    private external fun nativeIsLoaded(): Boolean
    private external fun nativeDumpConfig(): String

    // ─── Callback interface invoked from C++ ─────────────────────
    /**
     * JNI callback interface. Methods are invoked from the native C++ thread
     * via the LlmStreamBuffer → ostream interception pattern.
     *
     * Do NOT perform UI operations directly in these methods.
     */
    interface NativeTokenCallback {
        /** Called for each token/chunk written to the ostream by MNN (raw bytes). */
        fun onToken(token: ByteArray)
        /** Called when generation completes with the full assembled response. */
        fun onComplete(fullResponse: String)
        /** Called if an exception occurs during generation. */
        fun onError(error: String)
    }

    // ─── Public API ──────────────────────────────────────────────

    val isLoaded: Boolean get() = nativeIsLoaded()

    /**
     * Loads the MNN model from the given config JSON path.
     * This is a blocking I/O operation and runs on [Dispatchers.IO].
     *
     * @param configPath Absolute path to the MNN model config.json
     * @return true if the model was loaded successfully
     * @throws ModelLoadException if loading fails
     */
    suspend fun loadModel(configPath: String): Boolean = withContext(Dispatchers.IO) {
        Log.i(TAG, "Loading model from: $configPath")
        val success = nativeCreateLLM(configPath)
        if (!success) {
            throw ModelLoadException("Failed to load model from: $configPath")
        }
        Log.i(TAG, "Model loaded successfully")
        success
    }

    /**
     * Applies runtime configuration to the loaded model.
     *
     * @param configJson JSON string with MNN config overrides
     *   (e.g., `{"max_new_tokens": 2048, "temperature": 0.7}`)
     * @return true if config was applied successfully
     */
    fun setConfig(configJson: String): Boolean {
        return nativeSetConfig(configJson)
    }

    /**
     * Returns the model's current runtime configuration as a JSON string.
     */
    fun dumpConfig(): String = nativeDumpConfig()

    /**
     * Generates a streaming response for the given raw prompt string.
     *
     * Returns a cold [Flow<String>] that emits individual tokens as they are
     * generated by the MNN inference engine. The flow completes when generation
     * finishes or is cancelled.
     *
     * **Thread Safety:** The native generation runs synchronously on [Dispatchers.IO].
     * Token emissions via [callbackFlow] are safe to collect on any dispatcher.
     *
     * **Cancellation:** Cancelling the collecting coroutine scope will
     * signal the native engine to stop forwarding tokens.
     *
     * @param prompt The full prompt string (raw text — MNN does NOT apply chat template)
     * @return Flow emitting tokens as strings
     */
    fun generateStream(prompt: String): Flow<String> = callbackFlow {
        val byteBuffer = java.io.ByteArrayOutputStream()
        val callback = object : NativeTokenCallback {
            override fun onToken(token: ByteArray) {
                byteBuffer.write(token)
                trySend(String(byteBuffer.toByteArray(), Charsets.UTF_8))
            }

            override fun onComplete(fullResponse: String) {
                channel.close()
            }

            override fun onError(error: String) {
                close(InferenceException(error))
            }
        }

        // Run native generation on IO thread (blocks until complete)
        withContext(Dispatchers.IO) {
            nativeGenerateStream(prompt, callback)
        }

        awaitClose {
            Log.d(TAG, "Flow cancelled, requesting native cancellation")
            nativeCancelGeneration()
        }
    }

    /**
     * Generates a streaming response using multi-turn conversation history.
     *
     * This uses MNN's native [ChatMessages] API, which applies the model's
     * built-in chat template (e.g., Qwen's `<|im_start|>` tags, Llama's `[INST]`).
     * This is the preferred method for multi-turn conversations.
     *
     * @param messages List of role-content pairs: ("system", "..."), ("user", "..."), ("assistant", "...")
     * @return Flow emitting tokens as strings
     */
    fun generateWithHistory(messages: List<Pair<String, String>>): Flow<String> = callbackFlow {
        val roles = messages.map { it.first }.toTypedArray()
        val contents = messages.map { it.second }.toTypedArray()
        val byteBuffer = java.io.ByteArrayOutputStream()
        val callback = object : NativeTokenCallback {
            override fun onToken(token: ByteArray) {
                byteBuffer.write(token)
                trySend(String(byteBuffer.toByteArray(), Charsets.UTF_8))
            }

            override fun onComplete(fullResponse: String) {
                channel.close()
            }

            override fun onError(error: String) {
                close(InferenceException(error))
            }
        }

        withContext(Dispatchers.IO) {
            nativeGenerateWithHistory(roles, contents, callback)
        }

        awaitClose {
            Log.d(TAG, "History flow cancelled, requesting native cancellation")
            nativeCancelGeneration()
        }
    }

    /**
     * Cancels any ongoing generation.
     */
    fun cancelGeneration() {
        nativeCancelGeneration()
    }

    /**
     * Resets the conversation state (clears KV cache and history).
     * Call this when starting a new conversation topic.
     */
    fun resetConversation() {
        nativeReset()
    }

    /**
     * Releases the loaded model and frees all native memory.
     * Should be called when the model is no longer needed (e.g., onDestroy).
     */
    fun release() {
        Log.i(TAG, "Releasing model...")
        nativeCancelGeneration()
        nativeReleaseModel()
    }
}

// ─── Custom Exceptions ──────────────────────────────────────────────
class ModelLoadException(message: String) : RuntimeException(message)
class InferenceException(message: String) : RuntimeException(message)
